name: build_and_push
description: Command-line interface (CLI) build and push Flutter apps
version: 0.0.1
homepage: https://github.com/holyboom1/bnp.git

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.7.0
  get_it: ^8.0.3
  args: ^2.6.0
  dcli: ^6.1.0
  interact_cli: ^2.4.0
  json_ast: ^1.0.6
  convert: ^3.1.2
  equatable: ^2.0.7
  hive_ce: ^2.8.0+2
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  uuid: ^4.5.1

  retrofit: ^4.4.0
  json_annotation: ^4.9.0

dev_dependencies:
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0
  hive_ce_generator: ^1.8.1
  json_serializable: ^6.9.0
  build_runner: ^2.4.10
  lints: ^5.1.1


executables:
  bnp:

