// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:build_and_push/src/models/app_settings_model.dart';
import 'package:build_and_push/src/models/merge_request_model.dart';
import 'package:build_and_push/src/models/settings_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsModelAdapter());
    registerAdapter(MergeRequestModelAdapter());
    registerAdapter(SettingsModelAdapter());
  }
}
